<?php

// autoload_real.php @generated by Composer

class ComposerAutoloaderInitc1f6c59379838924d16658d7c8510caa
{
    private static $loader;

    public static function loadClassLoader($class)
    {
        if ('StripeWPFS\Composer\Autoload\ClassLoader' === $class) {
            require __DIR__ . '/ClassLoader.php';
        }
    }

    /**
     * @return \StripeWPFS\Composer\Autoload\ClassLoader
     */
    public static function getLoader()
    {
        if (null !== self::$loader) {
            return self::$loader;
        }

        require __DIR__ . '/platform_check.php';

        spl_autoload_register(array('ComposerAutoloaderInitc1f6c59379838924d16658d7c8510caa', 'loadClassLoader'), true, true);
        self::$loader = $loader = new \StripeWPFS\Composer\Autoload\ClassLoader(\dirname(__DIR__));
        spl_autoload_unregister(array('ComposerAutoloaderInitc1f6c59379838924d16658d7c8510caa', 'loadClassLoader'));

        require __DIR__ . '/autoload_static.php';
        call_user_func(\StripeWPFS\Composer\Autoload\ComposerStaticInitc1f6c59379838924d16658d7c8510caa::getInitializer($loader));

        $loader->setClassMapAuthoritative(true);
        $loader->register(true);

        return $loader;
    }
}
